from typing import Literal

from google.adk.agents import LlmAgent
from google.adk.models.lite_llm import LiteLlm
from google.adk.tools.mcp_tool import McpToolset
from google.adk.tools.mcp_tool.mcp_session_manager import (
    StreamableHTTPConnectionParams,
)
from pydantic import BaseModel, Field


class AgentResponse(BaseModel):
    """Agent response schema.

    Attributes:
        message: Message generated by the agent as response for user input.
        status: Status of the agent response.
            - completed: if the user's query has been answered
            - input-required: for clarifying questions to the user. Use if additional input is required from the user to answer the query
            - failed: Only if there was an error invoking tools.
    """

    message: str = Field(
        description='Message generated by the agent as response for user input'
    )
    status: Literal['completed', 'input-required', 'failed'] = Field(
        description='Status of the agent response'
    )


root_agent = LlmAgent(
    name='currency_agent',
    model=LiteLlm(model='openai/mistralai/mistral-medium-3-5'),
    description=('Currency Conversion agent'),
    instruction=(
        "You are an agent that helps with user's currency conversions. Use available tools to help with the conversion."
        'For currency conversions, do not assume target currencies. If user did not specify the target currency, ask for it.'
    ),
    tools=[
        McpToolset(
            connection_params=StreamableHTTPConnectionParams(
                url='http://localhost:8080/mcp'
            )
        )
    ],
    output_schema=AgentResponse,
)
